-- Add more columns to page_content table to store all page data
ALTER TABLE public.page_content 
ADD COLUMN IF NOT EXISTS price INTEGER,
ADD COLUMN IF NOT EXISTS mrp INTEGER,
ADD COLUMN IF NOT EXISTS gift_wrap_price INTEGER,
ADD COLUMN IF NOT EXISTS whatsapp_number TEXT,
ADD COLUMN IF NOT EXISTS order_by_date TEXT,
ADD COLUMN IF NOT EXISTS stock_count INTEGER;

-- Insert default content for all sections
INSERT INTO public.page_content (section, title, subtitle, description, button_text, button_link, price, mrp, gift_wrap_price, whatsapp_number, order_by_date, stock_count, content_json) VALUES
('topbar', 'Diwali Special', 'Free gift wrap', NULL, NULL, NULL, NULL, NULL, NULL, '919876543210', NULL, NULL, '{"payment_methods": "UPI • COD • Cards"}'),
('hero', 'This Diwali, gift her a little shine — earrings she''ll cherish', 'Gift wrap + handwritten note included', 'Order by 25th Oct for guaranteed Diwali delivery', 'Send as Diwali Gift — ₹699', '#price-section', 699, NULL, NULL, NULL, '25th Oct', NULL, '{"secondary_button": "Buy for Self", "badge_text": "Limited Diwali Collection", "benefits": ["30-day returns", "COD available"]}'),
('pricing', 'Special Diwali Pricing', 'Only 47 Diwali Gift Kits left', 'Save ₹300 (30% off)', 'Buy Now', NULL, 699, 999, 49, NULL, NULL, 47, '{"features": ["Premium Gift Wrap", "Handwritten Message (Free)", "Hide price on invoice"], "delivery_note": "Free delivery across India • Secure payment"}'),
('benefits', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"items": [{"icon": "Shield", "text": "Tarnish-resistant"}, {"icon": "Heart", "text": "Hypoallergenic"}, {"icon": "Gift", "text": "Gift box included"}, {"icon": "RotateCcw", "text": "30-day returns"}, {"icon": "Smartphone", "text": "COD & UPI"}]}'),
('why_choose_us', 'Why Choose Our Earrings?', 'Quality meets thoughtfulness — the perfect Diwali gift', NULL, NULL, NULL, NULL, NULL, NULL, '919876543210', NULL, NULL, '{"features": [{"icon": "Sparkles", "title": "Tarnish-Resistant Technology", "description": "Advanced coating ensures lasting shine. These aren''t ordinary earrings — they''re engineered to stay beautiful for years."}, {"icon": "Shield", "title": "30-Day Easy Returns", "description": "Not happy? Get a full refund within 30 days. We even cover return shipping. Zero risk, all reward."}, {"icon": "Clock", "title": "Fast Diwali Delivery", "description": "Order by 25th Oct for guaranteed delivery. Ships in 24 hours with tracking. Express options available."}, {"icon": "Award", "title": "Premium Quality, Fair Price", "description": "Direct-to-customer pricing means you get boutique quality at ₹699 instead of ₹2000+. No middlemen markup."}], "cta": {"title": "Still Have Questions?", "description": "Chat with us on WhatsApp for instant help. We''re here 9 AM - 9 PM daily.", "button_text": "Chat on WhatsApp"}}'),
('faq', 'Frequently Asked Questions', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{"items": [{"question": "Will these earrings tarnish?", "answer": "No! Our earrings feature an advanced tarnish-resistant coating that keeps them looking new for years. Even with regular wear, they maintain their beautiful shine. Simply store them in the provided satin pouch when not in use."}, {"question": "Can I return them if I''m gifting?", "answer": "Absolutely! We offer a 30-day hassle-free return policy. If the recipient doesn''t love them, they can easily return for a full refund. We''ll even help coordinate the return discreetly if it''s a gift."}, {"question": "How will the invoice be handled if I select hide price?", "answer": "When you check ''Hide price on invoice'', we''ll send the invoice to your email only. The package will include just the gift box with no pricing information, keeping your gift amount private."}, {"question": "What''s the last date to order for Diwali delivery?", "answer": "Order by 25th October to guarantee delivery before Diwali. We ship within 24 hours and delivery takes 3-5 days across India. Express shipping available for last-minute orders."}, {"question": "Are these safe for sensitive ears?", "answer": "Yes! The earring posts are hypoallergenic and nickel-free, making them perfect for sensitive ears. Many customers with metal allergies wear these comfortably every day."}, {"question": "What payment methods do you accept?", "answer": "We accept all major payment methods: UPI, Credit/Debit Cards, Net Banking, Wallets (Paytm, PhonePe, Google Pay), and Cash on Delivery (COD). All online payments are 100% secure."}]}')
ON CONFLICT DO NOTHING;